### ISSUE TITLE
its trying to find the file which was not created

### ISSUE THREAD

**Issue by kolet** [Va5c0/Steghide-Brute-Force-Tool#1]
ubuntu@ubuntu:~/Downloads/Steghide-Brute-Force-Tool$ sudo python steg_brute.py -b -d ../rockyou.txt -f 1.jpg

 [i] Searching...
  0%|                                                                                                        |

 steghide: could not extract any data with that passphrase!

 [+] Information obtained with password: 123456

Traceback (most recent call last):
  File "steg_brute.py", line 114, in <module>
    main()
  File "steg_brute.py", line 107, in main
    Steg_brute(args.file, args.dicc)
  File "steg_brute.py", line 51, in Steg_brute
    with open(ofile, 'r') as outfile:
IOError: [Errno 2] No such file or directory: '1_flag.txt'

and when creating the file by hand this is what i get

ubuntu@ubuntu:~/Downloads/Steghide-Brute-Force-Tool$ sudo python steg_brute.py -b -d ../rockyou.txt -f 1.jpg

 [i] Searching...
  0%|                                                                                                        |

 steghide: could not extract any data with that passphrase!

 [+] Information obtained with password: 123456

it does not go through all the wordlist it just stop after the first

**Comment by Va5c0** [comment]
Hi kolet, thanks for warning the errors. I have solved them, try again if it works.

**Comment by kolet** [comment]
hi! thanks for replying that still not working, (another issue)

ubuntu@ubuntu:~/Downloads/Steghide-Brute-Force-Tool$ sudo python steg_brute.py -b -d ../rockyou.txt -f 1.jpg

 [i] Searching...
  0%|                                                                                                                    |

 steghide: unknown argument "you".
steghide: type "steghide --help" for help.


 [+] Information obtained with password: rock you

ubuntu@ubuntu:~/Downloads/Steghide-Brute-Force-Tool$

**Comment by Va5c0** [comment]
The problem was the passwords with spaces, it is resolved, try again ;)

**Comment by Flokiv** [comment]
Hi@Hi-pc ~Steghide-Brute-Force-Tool-master $ ./steg_brute.py -b -d 1.txt -f ~/My.jpg

 [i] Searching...
  0%|                                                                                                                                                                  |
 steghide: impossible d'extraire des donn�es avec cette passphrase!
 [+] Information obtained with password: 123456
