### ISSUE TITLE
No module named 'progressbar'

### ISSUE THREAD

**Issue by DanielL99** [Va5c0/Steghide-Brute-Force-Tool#2]
I've tried to use your code on and get this error:

root@kali:~/Steghide-Brute-Force-Tool# python steg-brute.py -h
Traceball (most recent call last):
	File "steg_brute.py", line 4 in <module>
		from progressbar import ProgressBar, Percentage, Bar
ImportError: No module named 'progressbar'

**Comment by Va5c0** [comment]
Hi Daniel, install progressbar module with pip: `pip install progressbar`.

**Comment by DanielL99** [comment]
Wow, thanks

**Comment by ph3n0m79** [comment]
I am having a similar issue.  However, I installed progress bar with both pip and pip3.  The script then throws another error (below):
Traceback (most recent call last):
  File "steg_brute.py", line 123, in <module>
    main()
  File "steg_brute.py", line 116, in main
    Steg_brute(args.file, args.dicc)
  File "steg_brute.py", line 51, in Steg_brute
    pbar = progressbar(widgets=[Percentage(), Bar()], maxval=nlines).start()
TypeError: 'module' object is not callable

I did look on line 51 and changed it from ProgressBar(widgets.... to progressbar(widgets...
But there is still something not working properly.
Any hints?

**Comment by 0n1cOn3** [comment]
Use Python2 and pip2 to install the depencies. This resolves this issue
